# render.yaml para Cocoma-App (Versión Corregida)

# Primero, definimos los servicios (tu aplicación web)
services:
  - type: web
    name: cocoma-app
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan config:clear
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: cocoma-db # Se conecta a la base de datos definida abajo
          property: connectionString
      - key: FILESYSTEM_DISK
        value: s3
      # Las siguientes claves secretas se deben añadir manualmente en el Dashboard de Render
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
      - key: AWS_BUCKET
        sync: false

# Segundo, definimos las bases de datos
databases:
  - name: cocoma-db
    plan: free

